<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**assets
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->delete();
        $countries = [

            ["code" => "AD", "name_en" => "Andorra", "name_ar" => "أندورا", "flag" => env('APP_URL')."assets/Flags/ad.png"],
            ["code" => "AE", "name_en" => "United Arab Emirates", "name_ar" => "الإمارات العربية المتحدة", "flag" => env('APP_URL')."assets/Flags/ae.png"],
            ["code" => "AF", "name_en" => "Afghanistan", "name_ar" => "أفغانستان", "flag" => env('APP_URL')."assets/Flags/af.png"],
            ["code" => "AG", "name_en" => "Antigua and Barbuda", "name_ar" => "أنتيغوا وبربودا", "flag" => env('APP_URL')."assets/Flags/ag.png"],
            ["code" => "AI", "name_en" => "Anguilla", "name_ar" => "أنغويلا", "flag" => env('APP_URL')."assets/Flags/ai.png"],
            ["code" => "AL", "name_en" => "Albania", "name_ar" => "ألبانيا", "flag" => env('APP_URL')."assets/Flags/al.png"],
            ["code" => "AM", "name_en" => "Armenia", "name_ar" => "أرمينيا", "flag" => env('APP_URL')."assets/Flags/am.png"],
            ["code" => "AO", "name_en" => "Angola", "name_ar" => "أنغولا", "flag" => env('APP_URL')."assets/Flags/ao.png"],
            ["code" => "AQ", "name_en" => "Antarctica", "name_ar" => "القارة القطبية الجنوبية", "flag" => env('APP_URL')."assets/Flags/aq.png"],
            ["code" => "AR", "name_en" => "Argentina", "name_ar" => "الأرجنتين", "flag" => env('APP_URL')."assets/Flags/ar.png"],
            ["code" => "AS", "name_en" => "American Samoa", "name_ar" => "ساموا الأمريكية", "flag" => env('APP_URL')."assets/Flags/as.png"],
            ["code" => "AT", "name_en" => "Austria", "name_ar" => "النمسا", "flag" => env('APP_URL')."assets/Flags/at.png"],
            ["code" => "AU", "name_en" => "Australia", "name_ar" => "أستراليا", "flag" => env('APP_URL')."assets/Flags/au.png"],
            ["code" => "AW", "name_en" => "Aruba", "name_ar" => "أروبا", "flag" => env('APP_URL')."assets/Flags/aw.png"],
            ["code" => "AX", "name_en" => "Åland Islands", "name_ar" => "جزر آلاند", "flag" => env('APP_URL')."assets/Flags/ax.png"],
            ["code" => "AZ", "name_en" => "Azerbaijan", "name_ar" => "أذربيجان", "flag" => env('APP_URL')."assets/Flags/az.png"],
            ["code" => "BA", "name_en" => "Bosnia and Herzegovina", "name_ar" => "البوسنة والهرسك", "flag" => env('APP_URL')."assets/Flags/ba.png"],
            ["code" => "BB", "name_en" => "Barbados", "name_ar" => "باربادوس", "flag" => env('APP_URL')."assets/Flags/bb.png"],
            ["code" => "BD", "name_en" => "Bangladesh", "name_ar" => "بنغلاديش", "flag" => env('APP_URL')."assets/Flags/bd.png"],
            ["code" => "BE", "name_en" => "Belgium", "name_ar" => "بلجيكا", "flag" => env('APP_URL')."assets/Flags/be.png"],
            ["code" => "BF", "name_en" => "Burkina Faso", "name_ar" => "بوركينا فاسو", "flag" => env('APP_URL')."assets/Flags/bf.png"],
            ["code" => "BG", "name_en" => "Bulgaria", "name_ar" => "بلغاريا", "flag" => env('APP_URL')."assets/Flags/bg.png"],
            ["code" => "BH", "name_en" => "Bahrain", "name_ar" => "البحرين", "flag" => env('APP_URL')."assets/Flags/bh.png"],
            ["code" => "BI", "name_en" => "Burundi", "name_ar" => "بوروندي", "flag" => env('APP_URL')."assets/Flags/bi.png"],
            ["code" => "BJ", "name_en" => "Benin", "name_ar" => "بنين", "flag" => env('APP_URL')."assets/Flags/bj.png"],
            ["code" => "BL", "name_en" => "Saint Barthélemy", "name_ar" => "سانت بارثيليمي", "flag" => env('APP_URL')."assets/Flags/bl.png"],
            ["code" => "BM", "name_en" => "Bermuda", "name_ar" => "برمودا", "flag" => env('APP_URL')."assets/Flags/bm.png"],
            ["code" => "BN", "name_en" => "Brunei Darussalam", "name_ar" => "بروناي دار السلام", "flag" => env('APP_URL')."assets/Flags/bn.png"],
            ["code" => "BO", "name_en" => "Bolivia, Plurinational State of", "name_ar" => "بوليفيا، دولة متعددة القوميات", "flag" => env('APP_URL')."assets/Flags/bo.png"],
            ["code" => "BQ", "name_en" => "Caribbean Netherlands", "name_ar" => "هولندا الكاريبية", "flag" => env('APP_URL')."assets/Flags/bq.png"],
            ["code" => "BR", "name_en" => "Brazil", "name_ar" => "البرازيل", "flag" => env('APP_URL')."assets/Flags/br.png"],
            ["code" => "BS", "name_en" => "Bahamas", "name_ar" => "الباهاماس", "flag" => env('APP_URL')."assets/Flags/bs.png"],
            ["code" => "BT", "name_en" => "Bhutan", "name_ar" => "بوتان", "flag" => env('APP_URL')."assets/Flags/bt.png"],
            ["code" => "BV", "name_en" => "Bouvet Island", "name_ar" => "جزيرة بوفيت", "flag" => env('APP_URL')."assets/Flags/bv.png"],
            ["code" => "BW", "name_en" => "Botswana", "name_ar" => "بوتسوانا", "flag" => env('APP_URL')."assets/Flags/bw.png"],
            ["code" => "BY", "name_en" => "Belarus", "name_ar" => "بيلاروسيا", "flag" => env('APP_URL')."assets/Flags/by.png"],
            ["code" => "BZ", "name_en" => "Belize", "name_ar" => "بليز", "flag" => env('APP_URL')."assets/Flags/bz.png"],
            ["code" => "CA", "name_en" => "Canada", "name_ar" => "كندا", "flag" => env('APP_URL')."assets/Flags/ca.png"],
            ["code" => "CC", "name_en" => "Cocos (Keeling) Islands", "name_ar" => "جزر كوكوس (كيلينغ)", "flag" => env('APP_URL')."assets/Flags/cc.png"],
            ["code" => "CD", "name_en" => "Congo, the Democratic Republic of the", "name_ar" => "الكونغو، جمهورية الكونغو الديمقراطية", "flag" => env('APP_URL')."assets/Flags/cd.png"],
            ["code" => "CF", "name_en" => "Central African Republic", "name_ar" => "جمهورية أفريقيا الوسطى", "flag" => env('APP_URL')."assets/Flags/cf.png"],
            ["code" => "CG", "name_en" => "Republic of the Congo", "name_ar" => "جمهورية الكونغو", "flag" => env('APP_URL')."assets/Flags/cg.png"],
            ["code" => "CH", "name_en" => "Switzerland", "name_ar" => "سويسرا", "flag" => env('APP_URL')."assets/Flags/ch.png"],
            ["code" => "CI", "name_en" => "Côte d'Ivoire", "name_ar" => "ساحل العاج", "flag" => env('APP_URL')."assets/Flags/ci.png"],
            ["code" => "CK", "name_en" => "Cook Islands", "name_ar" => "جزر كوك", "flag" => env('APP_URL')."assets/Flags/ck.png"],
            ["code" => "CL", "name_en" => "Chile", "name_ar" => "تشيلي", "flag" => env('APP_URL')."assets/Flags/cl.png"],
            ["code" => "CM", "name_en" => "Cameroon", "name_ar" => "الكاميرون", "flag" => env('APP_URL')."assets/Flags/cm.png"],
            ["code" => "CN", "name_en" => "China (People's Republic of China)", "name_ar" => "الصين (جمهورية الصين الشعبية)", "flag" => env('APP_URL')."assets/Flags/cn.png"],
            ["code" => "CO", "name_en" => "Colombia", "name_ar" => "كولومبيا", "flag" => env('APP_URL')."assets/Flags/co.png"],
            ["code" => "CR", "name_en" => "Costa Rica", "name_ar" => "كوستاريكا", "flag" => env('APP_URL')."assets/Flags/cr.png"],
            ["code" => "CU", "name_en" => "Cuba", "name_ar" => "كوبا", "flag" => env('APP_URL')."assets/Flags/cu.png"],
            ["code" => "CV", "name_en" => "Cape Verde", "name_ar" => "الرأس الأخضر", "flag" => env('APP_URL')."assets/Flags/cv.png"],
            ["code" => "CW", "name_en" => "Curaçao", "name_ar" => "كوراساو", "flag" => env('APP_URL')."assets/Flags/cw.png"],
            ["code" => "CX", "name_en" => "Christmas Island", "name_ar" => "جزيرة الكريسماس", "flag" => env('APP_URL')."assets/Flags/cx.png"],
            ["code" => "CY", "name_en" => "Cyprus", "name_ar" => "قبرص", "flag" => env('APP_URL')."assets/Flags/cy.png"],
            ["code" => "CZ", "name_en" => "Czech Republic", "name_ar" => "جمهورية التشيك", "flag" => env('APP_URL')."assets/Flags/cz.png"],
            ["code" => "DE", "name_en" => "Germany", "name_ar" => "ألمانيا", "flag" => env('APP_URL')."assets/Flags/de.png"],
            ["code" => "DJ", "name_en" => "Djibouti", "name_ar" => "جيبوتي", "flag" => env('APP_URL')."assets/Flags/dj.png"],
            ["code" => "DK", "name_en" => "Denmark", "name_ar" => "الدنمارك", "flag" => env('APP_URL')."assets/Flags/dk.png"],
            ["code" => "DM", "name_en" => "Dominica", "name_ar" => "دومينيكا", "flag" => env('APP_URL')."assets/Flags/dm.png"],
            ["code" => "DO", "name_en" => "Dominican Republic", "name_ar" => "جمهورية الدومينيكان", "flag" => env('APP_URL')."assets/Flags/do.png"],
            ["code" => "DZ", "name_en" => "Algeria", "name_ar" => "الجزائر", "flag" => env('APP_URL')."assets/Flags/dz.png"],
            ["code" => "EC", "name_en" => "Ecuador", "name_ar" => "الإكوادور", "flag" => env('APP_URL')."assets/Flags/ec.png"],
            ["code" => "EE", "name_en" => "Estonia", "name_ar" => "إستونيا", "flag" => env('APP_URL')."assets/Flags/ee.png"],
            ["code" => "EG", "name_en" => "Egypt", "name_ar" => "مصر", "flag" => env('APP_URL')."assets/Flags/eg.png"],
            ["code" => "EH", "name_en" => "Western Sahara", "name_ar" => "الصحراء الغربية", "flag" => env('APP_URL')."assets/Flags/eh.png"],
            ["code" => "ER", "name_en" => "Eritrea", "name_ar" => "إريتريا", "flag" => env('APP_URL')."assets/Flags/er.png"],
            ["code" => "ES", "name_en" => "Spain", "name_ar" => "إسبانيا", "flag" => env('APP_URL')."assets/Flags/es.png"],
            ["code" => "ET", "name_en" => "Ethiopia", "name_ar" => "إثيوبيا", "flag" => env('APP_URL')."assets/Flags/et.png"],
            ["code" => "EU", "name_en" => "Europe", "name_ar" => "أوروبا", "flag" => env('APP_URL')."assets/Flags/eu.png"],
            ["code" => "FI", "name_en" => "Finland", "name_ar" => "فنلندا", "flag" => env('APP_URL')."assets/Flags/fi.png"],
            ["code" => "FJ", "name_en" => "Fiji", "name_ar" => "فيجي", "flag" => env('APP_URL')."assets/Flags/fj.png"],
            ["code" => "FK", "name_en" => "Falkland Islands (Malvinas)", "name_ar" => "جزر فوكلاند (مالفينا)", "flag" => env('APP_URL')."assets/Flags/fk.png"],
            ["code" => "FM", "name_en" => "Micronesia, Federated States of", "name_ar" => "ميكرونيزيا، الولايات الفيدرالية", "flag" => env('APP_URL')."assets/Flags/fm.png"],
            ["code" => "FO", "name_en" => "Faroe Islands", "name_ar" => "جزر فارو", "flag" => env('APP_URL')."assets/Flags/fo.png"],
            ["code" => "FR", "name_en" => "France", "name_ar" => "فرنسا", "flag" => env('APP_URL')."assets/Flags/fr.png"],
            ["code" => "GA", "name_en" => "Gabon", "name_ar" => "الغابون", "flag" => env('APP_URL')."assets/Flags/ga.png"],
            ["code" => "GB-NG", "name_en" => "England", "name_ar" => "إنجلترا", "flag" => env('APP_URL')."gb-assets/Flags/ng.png"],
            ["code" => "GB-IR", "name_en" => "Northern Ireland", "name_ar" => "إيرلندا الشمالية", "flag" => env('APP_URL')."gb-assets/Flags/ir.png"],
            ["code" => "GB-CT", "name_en" => "Scotland", "name_ar" => "اسكتلندا", "flag" => env('APP_URL')."gb-assets/Flags/ct.png"],
            ["code" => "GB-LS", "name_en" => "Wales", "name_ar" => "ويلز", "flag" => env('APP_URL')."gb-assets/Flags/ls.png"],
            ["code" => "GB", "name_en" => "United Kingdom", "name_ar" => "المملكة المتحدة", "flag" => env('APP_URL')."assets/Flags/gb.png"],
            ["code" => "GD", "name_en" => "Grenada", "name_ar" => "غرينادا", "flag" => env('APP_URL')."assets/Flags/gd.png"],
            ["code" => "GE", "name_en" => "Georgia", "name_ar" => "جورجيا", "flag" => env('APP_URL')."assets/Flags/ge.png"],
            ["code" => "GF", "name_en" => "French Guiana", "name_ar" => "غويانا الفرنسية", "flag" => env('APP_URL')."assets/Flags/gf.png"],
            ["code" => "GG", "name_en" => "Guernsey", "name_ar" => "غيرنزي", "flag" => env('APP_URL')."assets/Flags/gg.png"],
            ["code" => "GH", "name_en" => "Ghana", "name_ar" => "غانا", "flag" => env('APP_URL')."assets/Flags/gh.png"],
            ["code" => "GI", "name_en" => "Gibraltar", "name_ar" => "جبل طارق", "flag" => env('APP_URL')."assets/Flags/gi.png"],
            ["code" => "GL", "name_en" => "Greenland", "name_ar" => "غرينلاند", "flag" => env('APP_URL')."assets/Flags/gl.png"],
            ["code" => "GM", "name_en" => "Gambia", "name_ar" => "غامبيا", "flag" => env('APP_URL')."assets/Flags/gm.png"],
            ["code" => "GN", "name_en" => "Guinea", "name_ar" => "غينيا", "flag" => env('APP_URL')."assets/Flags/gn.png"],
            ["code" => "GP", "name_en" => "Guadeloupe", "name_ar" => "غوادلوب", "flag" => env('APP_URL')."assets/Flags/gp.png"],
            ["code" => "GQ", "name_en" => "Equatorial Guinea", "name_ar" => "غينيا الاستوائية", "flag" => env('APP_URL')."assets/Flags/gq.png"],
            ["code" => "GR", "name_en" => "Greece", "name_ar" => "اليونان", "flag" => env('APP_URL')."assets/Flags/gr.png"],
            ["code" => "GS", "name_en" => "South Georgia and the South Sandwich Islands", "name_ar" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "flag" => env('APP_URL')."assets/Flags/gs.png"],
            ["code" => "GT", "name_en" => "Guatemala", "name_ar" => "غواتيمالا", "flag" => env('APP_URL')."assets/Flags/gt.png"],
            ["code" => "GU", "name_en" => "Guam", "name_ar" => "غوام", "flag" => env('APP_URL')."assets/Flags/gu.png"],
            ["code" => "GW", "name_en" => "Guinea-Bissau", "name_ar" => "غينيا بيساو", "flag" => env('APP_URL')."assets/Flags/gw.png"],
            ["code" => "GY", "name_en" => "Guyana", "name_ar" => "غويانا", "flag" => env('APP_URL')."assets/Flags/gy.png"],
            ["code" => "HK", "name_en" => "Hong Kong", "name_ar" => "هونغ كونغ", "flag" => env('APP_URL')."assets/Flags/hk.png"],
            ["code" => "HM", "name_en" => "Heard Island and McDonald Islands", "name_ar" => "جزيرة هيرد وجزر ماكدونالد", "flag" => env('APP_URL')."assets/Flags/hm.png"],
            ["code" => "HN", "name_en" => "Honduras", "name_ar" => "هندوراس", "flag" => env('APP_URL')."assets/Flags/hn.png"],
            ["code" => "HR", "name_en" => "Croatia", "name_ar" => "كرواتيا", "flag" => env('APP_URL')."assets/Flags/hr.png"],
            ["code" => "HT", "name_en" => "Haiti", "name_ar" => "هايتي", "flag" => env('APP_URL')."assets/Flags/ht.png"],
            ["code" => "HU", "name_en" => "Hungary", "name_ar" => "هنغاريا", "flag" => env('APP_URL')."assets/Flags/hu.png"],
            ["code" => "ID", "name_en" => "Indonesia", "name_ar" => "إندونيسيا", "flag" => env('APP_URL')."assets/Flags/id.png"],
            ["code" => "IE", "name_en" => "Ireland", "name_ar" => "أيرلندا", "flag" => env('APP_URL')."assets/Flags/ie.png"],
            ["code" => "IL", "name_en" => "Israel", "name_ar" => "إسرائيل", "flag" => env('APP_URL')."assets/Flags/il.png"],
            ["code" => "IM", "name_en" => "Isle of Man", "name_ar" => "جزيرة مان", "flag" => env('APP_URL')."assets/Flags/im.png"],
            ["code" => "IN", "name_en" => "India", "name_ar" => "الهند", "flag" => env('APP_URL')."assets/Flags/in.png"],
            ["code" => "IO", "name_en" => "British Indian Ocean Territory", "name_ar" => "إقليم المحيط الهندي البريطاني", "flag" => env('APP_URL')."assets/Flags/io.png"],
            ["code" => "IQ", "name_en" => "Iraq", "name_ar" => "العراق", "flag" => env('APP_URL')."assets/Flags/iq.png"],
            ["code" => "IR", "name_en" => "Iran, Islamic Republic of", "name_ar" => "إيران، الجمهورية الإسلامية", "flag" => env('APP_URL')."assets/Flags/ir.png"],
            ["code" => "IS", "name_en" => "Iceland", "name_ar" => "آيسلندا", "flag" => env('APP_URL')."assets/Flags/is.png"],
            ["code" => "IT", "name_en" => "Italy", "name_ar" => "إيطاليا", "flag" => env('APP_URL')."assets/Flags/it.png"],
            ["code" => "JE", "name_en" => "Jersey", "name_ar" => "جيرسي", "flag" => env('APP_URL')."assets/Flags/je.png"],
            ["code" => "JM", "name_en" => "Jamaica", "name_ar" => "جامايكا", "flag" => env('APP_URL')."assets/Flags/jm.png"],
            ["code" => "JO", "name_en" => "Jordan", "name_ar" => "الأردن", "flag" => env('APP_URL')."assets/Flags/jo.png"],
            ["code" => "JP", "name_en" => "Japan", "name_ar" => "اليابان", "flag" => env('APP_URL')."assets/Flags/jp.png"],
            ["code" => "KE", "name_en" => "Kenya", "name_ar" => "كينيا", "flag" => env('APP_URL')."assets/Flags/ke.png"],
            ["code" => "KG", "name_en" => "Kyrgyzstan", "name_ar" => "قيرغيزستان", "flag" => env('APP_URL')."assets/Flags/kg.png"],
            ["code" => "KH", "name_en" => "Cambodia", "name_ar" => "كمبوديا", "flag" => env('APP_URL')."assets/Flags/kh.png"],
            ["code" => "KI", "name_en" => "Kiribati", "name_ar" => "كيريباتي", "flag" => env('APP_URL')."assets/Flags/ki.png"],
            ["code" => "KM", "name_en" => "Comoros", "name_ar" => "جزر القمر", "flag" => env('APP_URL')."assets/Flags/km.png"],
            ["code" => "KN", "name_en" => "Saint Kitts and Nevis", "name_ar" => "سانت كيتس ونيفيس", "flag" => env('APP_URL')."assets/Flags/kn.png"],
            ["code" => "KP", "name_en" => "Korea, Democratic People's Republic of", "name_ar" => "كوريا، جمهورية كوريا الديمقراطية الشعبية", "flag" => env('APP_URL')."assets/Flags/kp.png"],
            ["code" => "KR", "name_en" => "Korea, Republic of", "name_ar" => "كوريا، جمهورية كوريا", "flag" => env('APP_URL')."assets/Flags/kr.png"],
            ["code" => "KW", "name_en" => "Kuwait", "name_ar" => "الكويت", "flag" => env('APP_URL')."assets/Flags/kw.png"],
            ["code" => "KY", "name_en" => "Cayman Islands", "name_ar" => "جزر كايمان", "flag" => env('APP_URL')."assets/Flags/ky.png"],
            ["code" => "KZ", "name_en" => "Kazakhstan", "name_ar" => "كازاخستان", "flag" => env('APP_URL')."assets/Flags/kz.png"],
            ["code" => "LA", "name_en" => "Laos (Lao People's Democratic Republic)", "name_ar" => "لاوس (جمهورية لاو الديمقراطية الشعبية)", "flag" => env('APP_URL')."assets/Flags/la.png"],
            ["code" => "LB", "name_en" => "Lebanon", "name_ar" => "لبنان", "flag" => env('APP_URL')."assets/Flags/lb.png"],
            ["code" => "LC", "name_en" => "Saint Lucia", "name_ar" => "سانت لوسيا", "flag" => env('APP_URL')."assets/Flags/lc.png"],
            ["code" => "LI", "name_en" => "Liechtenstein", "name_ar" => "ليختنشتاين", "flag" => env('APP_URL')."assets/Flags/li.png"],
            ["code" => "LK", "name_en" => "Sri Lanka", "name_ar" => "سريلانكا", "flag" => env('APP_URL')."assets/Flags/lk.png"],
            ["code" => "LR", "name_en" => "Liberia", "name_ar" => "ليبيريا", "flag" => env('APP_URL')."assets/Flags/lr.png"],
            ["code" => "LS", "name_en" => "Lesotho", "name_ar" => "ليسوتو", "flag" => env('APP_URL')."assets/Flags/ls.png"],
            ["code" => "LT", "name_en" => "Lithuania", "name_ar" => "ليتوانيا", "flag" => env('APP_URL')."assets/Flags/lt.png"],
            ["code" => "LU", "name_en" => "Luxembourg", "name_ar" => "لوكسمبورغ", "flag" => env('APP_URL')."assets/Flags/lu.png"],
            ["code" => "LV", "name_en" => "Latvia", "name_ar" => "لاتفيا", "flag" => env('APP_URL')."assets/Flags/lv.png"],
            ["code" => "LY", "name_en" => "Libya", "name_ar" => "ليبيا", "flag" => env('APP_URL')."assets/Flags/ly.png"],
            ["code" => "MA", "name_en" => "Morocco", "name_ar" => "المغرب", "flag" => env('APP_URL')."assets/Flags/ma.png"],
            ["code" => "MC", "name_en" => "Monaco", "name_ar" => "موناكو", "flag" => env('APP_URL')."assets/Flags/mc.png"],
            ["code" => "MD", "name_en" => "Moldova, Republic of", "name_ar" => "مولدوفا، جمهورية", "flag" => env('APP_URL')."assets/Flags/md.png"],
            ["code" => "ME", "name_en" => "Montenegro", "name_ar" => "مونتينيغرو", "flag" => env('APP_URL')."assets/Flags/me.png"],
            ["code" => "MF", "name_en" => "Saint Martin", "name_ar" => "سانت مارتن", "flag" => env('APP_URL')."assets/Flags/mf.png"],
            ["code" => "MG", "name_en" => "Madagascar", "name_ar" => "مدغشقر", "flag" => env('APP_URL')."assets/Flags/mg.png"],
            ["code" => "MH", "name_en" => "Marshall Islands", "name_ar" => "جزر مارشال", "flag" => env('APP_URL')."assets/Flags/mh.png"],
            ["code" => "MK", "name_en" => "North Macedonia", "name_ar" => "مقدونيا الشمالية", "flag" => env('APP_URL')."assets/Flags/mk.png"],
            ["code" => "ML", "name_en" => "Mali", "name_ar" => "مالي", "flag" => env('APP_URL')."assets/Flags/ml.png"],
            ["code" => "MM", "name_en" => "Myanmar", "name_ar" => "ميانمار", "flag" => env('APP_URL')."assets/Flags/mm.png"],
            ["code" => "MN", "name_en" => "Mongolia", "name_ar" => "منغوليا", "flag" => env('APP_URL')."assets/Flags/mn.png"],
            ["code" => "MO", "name_en" => "Macao", "name_ar" => "ماكاو", "flag" => env('APP_URL')."assets/Flags/mo.png"],
            ["code" => "MP", "name_en" => "Northern Mariana Islands", "name_ar" => "جزر ماريانا الشمالية", "flag" => env('APP_URL')."assets/Flags/mp.png"],
            ["code" => "MQ", "name_en" => "Martinique", "name_ar" => "مارتينيك", "flag" => env('APP_URL')."assets/Flags/mq.png"],
            ["code" => "MR", "name_en" => "Mauritania", "name_ar" => "موريتانيا", "flag" => env('APP_URL')."assets/Flags/mr.png"],
            ["code" => "MS", "name_en" => "Montserrat", "name_ar" => "مونتسيرات", "flag" => env('APP_URL')."assets/Flags/ms.png"],
            ["code" => "MT", "name_en" => "Malta", "name_ar" => "مالطا", "flag" => env('APP_URL')."assets/Flags/mt.png"],
            ["code" => "MU", "name_en" => "Mauritius", "name_ar" => "موريشيوس", "flag" => env('APP_URL')."assets/Flags/mu.png"],
            ["code" => "MV", "name_en" => "Maldives", "name_ar" => "جزر المالديف", "flag" => env('APP_URL')."assets/Flags/mv.png"],
            ["code" => "MW", "name_en" => "Malawi", "name_ar" => "مالاوي", "flag" => env('APP_URL')."assets/Flags/mw.png"],
            ["code" => "MX", "name_en" => "Mexico", "name_ar" => "المكسيك", "flag" => env('APP_URL')."assets/Flags/mx.png"],
            ["code" => "MY", "name_en" => "Malaysia", "name_ar" => "ماليزيا", "flag" => env('APP_URL')."assets/Flags/my.png"],
            ["code" => "MZ", "name_en" => "Mozambique", "name_ar" => "موزمبيق", "flag" => env('APP_URL')."assets/Flags/mz.png"],
            ["code" => "NA", "name_en" => "Namibia", "name_ar" => "ناميبيا", "flag" => env('APP_URL')."assets/Flags/na.png"],
            ["code" => "NC", "name_en" => "New Caledonia", "name_ar" => "كاليدونيا الجديدة", "flag" => env('APP_URL')."assets/Flags/nc.png"],
            ["code" => "NE", "name_en" => "Niger", "name_ar" => "النيجر", "flag" => env('APP_URL')."assets/Flags/ne.png"],
            ["code" => "NF", "name_en" => "Norfolk Island", "name_ar" => "جزيرة نورفولك", "flag" => env('APP_URL')."assets/Flags/nf.png"],
            ["code" => "NG", "name_en" => "Nigeria", "name_ar" => "نيجيريا", "flag" => env('APP_URL')."assets/Flags/ng.png"],
            ["code" => "NI", "name_en" => "Nicaragua", "name_ar" => "نيكاراغوا", "flag" => env('APP_URL')."assets/Flags/ni.png"],
            ["code" => "NL", "name_en" => "Netherlands", "name_ar" => "هولندا", "flag" => env('APP_URL')."assets/Flags/nl.png"],
            ["code" => "NO", "name_en" => "Norway", "name_ar" => "النرويج", "flag" => env('APP_URL')."assets/Flags/no.png"],
            ["code" => "NP", "name_en" => "Nepal", "name_ar" => "نيبال", "flag" => env('APP_URL')."assets/Flags/np.png"],
            ["code" => "NR", "name_en" => "Nauru", "name_ar" => "ناورو", "flag" => env('APP_URL')."assets/Flags/nr.png"],
            ["code" => "NU", "name_en" => "Niue", "name_ar" => "نيوي", "flag" => env('APP_URL')."assets/Flags/nu.png"],
            ["code" => "NZ", "name_en" => "New Zealand", "name_ar" => "نيوزيلندا", "flag" => env('APP_URL')."assets/Flags/nz.png"],
            ["code" => "OM", "name_en" => "Oman", "name_ar" => "عمان", "flag" => env('APP_URL')."assets/Flags/om.png"],
            ["code" => "PA", "name_en" => "Panama", "name_ar" => "بنما", "flag" => env('APP_URL')."assets/Flags/pa.png"],
            ["code" => "PE", "name_en" => "Peru", "name_ar" => "بيرو", "flag" => env('APP_URL')."assets/Flags/pe.png"],
            ["code" => "PF", "name_en" => "French Polynesia", "name_ar" => "بولينيزيا الفرنسية", "flag" => env('APP_URL')."assets/Flags/pf.png"],
            ["code" => "PG", "name_en" => "Papua New Guinea", "name_ar" => "بابوا غينيا الجديدة", "flag" => env('APP_URL')."assets/Flags/pg.png"],
            ["code" => "PH", "name_en" => "Philippines", "name_ar" => "الفلبين", "flag" => env('APP_URL')."assets/Flags/ph.png"],
            ["code" => "PK", "name_en" => "Pakistan", "name_ar" => "باكستان", "flag" => env('APP_URL')."assets/Flags/pk.png"],
            ["code" => "PL", "name_en" => "Poland", "name_ar" => "بولندا", "flag" => env('APP_URL')."assets/Flags/pl.png"],
            ["code" => "PM", "name_en" => "Saint Pierre and Miquelon", "name_ar" => "سانت بيير وميكيلون", "flag" => env('APP_URL')."assets/Flags/pm.png"],
            ["code" => "PN", "name_en" => "Pitcairn", "name_ar" => "بيتكيرن", "flag" => env('APP_URL')."assets/Flags/pn.png"],
            ["code" => "PR", "name_en" => "Puerto Rico", "name_ar" => "بورتو ريكو", "flag" => env('APP_URL')."assets/Flags/pr.png"],
            ["code" => "PS", "name_en" => "Palestine", "name_ar" => "فلسطين", "flag" => env('APP_URL')."assets/Flags/ps.png"],
            ["code" => "PT", "name_en" => "Portugal", "name_ar" => "البرتغال", "flag" => env('APP_URL')."assets/Flags/pt.png"],
            ["code" => "PW", "name_en" => "Palau", "name_ar" => "بالاو", "flag" => env('APP_URL')."assets/Flags/pw.png"],
            ["code" => "PY", "name_en" => "Paraguay", "name_ar" => "باراغواي", "flag" => env('APP_URL')."assets/Flags/py.png"],
            ["code" => "QA", "name_en" => "Qatar", "name_ar" => "قطر", "flag" => env('APP_URL')."assets/Flags/qa.png"],
            ["code" => "RE", "name_en" => "Réunion", "name_ar" => "ريونيون", "flag" => env('APP_URL')."assets/Flags/re.png"],
            ["code" => "RO", "name_en" => "Romania", "name_ar" => "رومانيا", "flag" => env('APP_URL')."assets/Flags/ro.png"],
            ["code" => "RS", "name_en" => "Serbia", "name_ar" => "صربيا", "flag" => env('APP_URL')."assets/Flags/rs.png"],
            ["code" => "RU", "name_en" => "Russian Federation", "name_ar" => "الاتحاد الروسي", "flag" => env('APP_URL')."assets/Flags/ru.png"],
            ["code" => "RW", "name_en" => "Rwanda", "name_ar" => "رواندا", "flag" => env('APP_URL')."assets/Flags/rw.png"],
            ["code" => "SA", "name_en" => "Saudi Arabia", "name_ar" => "المملكة العربية السعودية", "flag" => env('APP_URL')."assets/Flags/sa.png"],
            ["code" => "SB", "name_en" => "Solomon Islands", "name_ar" => "جزر سليمان", "flag" => env('APP_URL')."assets/Flags/sb.png"],
            ["code" => "SC", "name_en" => "Seychelles", "name_ar" => "سيشيل", "flag" => env('APP_URL')."assets/Flags/sc.png"],
            ["code" => "SD", "name_en" => "Sudan", "name_ar" => "السودان", "flag" => env('APP_URL')."assets/Flags/sd.png"],
            ["code" => "SE", "name_en" => "Sweden", "name_ar" => "السويد", "flag" => env('APP_URL')."assets/Flags/se.png"],
            ["code" => "SG", "name_en" => "Singapore", "name_ar" => "سنغافورة", "flag" => env('APP_URL')."assets/Flags/sg.png"],
            ["code" => "SH", "name_en" => "Saint Helena, Ascension and Tristan da Cunha", "name_ar" => "سانت هيلينا، آسيجنشن وتريستان دا كونها", "flag" => env('APP_URL')."assets/Flags/sh.png"],
            ["code" => "SI", "name_en" => "Slovenia", "name_ar" => "سلوفينيا", "flag" => env('APP_URL')."assets/Flags/si.png"],
            ["code" => "SJ", "name_en" => "Svalbard and Jan Mayen Islands", "name_ar" => "جزر سفالبارد ويان ماين", "flag" => env('APP_URL')."assets/Flags/sj.png"],
            ["code" => "SK", "name_en" => "Slovakia", "name_ar" => "سلوفاكيا", "flag" => env('APP_URL')."assets/Flags/sk.png"],
            ["code" => "SL", "name_en" => "Sierra Leone", "name_ar" => "سيراليون", "flag" => env('APP_URL')."assets/Flags/sl.png"],
            ["code" => "SM", "name_en" => "San Marino", "name_ar" => "سان مارينو", "flag" => env('APP_URL')."assets/Flags/sm.png"],
            ["code" => "SN", "name_en" => "Senegal", "name_ar" => "السنغال", "flag" => env('APP_URL')."assets/Flags/sn.png"],
            ["code" => "SO", "name_en" => "Somalia", "name_ar" => "الصومال", "flag" => env('APP_URL')."assets/Flags/so.png"],
            ["code" => "SR", "name_en" => "Suriname", "name_ar" => "سورينام", "flag" => env('APP_URL')."assets/Flags/sr.png"],
            ["code" => "SS", "name_en" => "South Sudan", "name_ar" => "جنوب السودان", "flag" => env('APP_URL')."assets/Flags/ss.png"],
            ["code" => "ST", "name_en" => "Sao Tome and Principe", "name_ar" => "ساو تومي وبرينسيبي", "flag" => env('APP_URL')."assets/Flags/st.png"],
            ["code" => "SV", "name_en" => "El Salvador", "name_ar" => "السلفادور", "flag" => env('APP_URL')."assets/Flags/sv.png"],
            ["code" => "SX", "name_en" => "Sint Maarten (Dutch part)", "name_ar" => "سانت مارتن (الجزء الهولندي)", "flag" => env('APP_URL')."assets/Flags/sx.png"],
            ["code" => "SY", "name_en" => "Syrian Arab Republic", "name_ar" => "الجمهورية العربية السورية", "flag" => env('APP_URL')."assets/Flags/sy.png"],
            ["code" => "SZ", "name_en" => "Kingdom of Eswatini", "name_ar" => "مملكة إسواتيني", "flag" => env('APP_URL')."assets/Flags/sz.png"],
            ["code" => "TC", "name_en" => "Turks and Caicos Islands", "name_ar" => "جزر توركس وكايكوس", "flag" => env('APP_URL')."assets/Flags/tc.png"],
            ["code" => "TD", "name_en" => "Chad", "name_ar" => "تشاد", "flag" => env('APP_URL')."assets/Flags/td.png"],
            ["code" => "TF", "name_en" => "French Southern Territories", "name_ar" => "الأقاليم الجنوبية الفرنسية", "flag" => env('APP_URL')."assets/Flags/tf.png"],
            ["code" => "TG", "name_en" => "Togo", "name_ar" => "توغو", "flag" => env('APP_URL')."assets/Flags/tg.png"],
            ["code" => "TH", "name_en" => "Thailand", "name_ar" => "تايلاند", "flag" => env('APP_URL')."assets/Flags/th.png"],
            ["code" => "TJ", "name_en" => "Tajikistan", "name_ar" => "طاجيكستان", "flag" => env('APP_URL')."assets/Flags/tj.png"],
            ["code" => "TK", "name_en" => "Tokelau", "name_ar" => "توكيلو", "flag" => env('APP_URL')."assets/Flags/tk.png"],
            ["code" => "TL", "name_en" => "Timor-Leste", "name_ar" => "تيمور الشرقية", "flag" => env('APP_URL')."assets/Flags/tl.png"],
            ["code" => "TM", "name_en" => "Turkmenistan", "name_ar" => "تركمانستان", "flag" => env('APP_URL')."assets/Flags/tm.png"],
            ["code" => "TN", "name_en" => "Tunisia", "name_ar" => "تونس", "flag" => env('APP_URL')."assets/Flags/tn.png"],
            ["code" => "TO", "name_en" => "Tonga", "name_ar" => "تونغا", "flag" => env('APP_URL')."assets/Flags/to.png"],
            ["code" => "TR", "name_en" => "Republic of Türkiye", "name_ar" => "جمهورية تركيا", "flag" => env('APP_URL')."assets/Flags/tr.png"],
            ["code" => "TT", "name_en" => "Trinidad and Tobago", "name_ar" => "ترينيداد وتوباغو", "flag" => env('APP_URL')."assets/Flags/tt.png"],
            ["code" => "TV", "name_en" => "Tuvalu", "name_ar" => "توفالو", "flag" => env('APP_URL')."assets/Flags/tv.png"],
            ["code" => "TW", "name_en" => "Taiwan (Republic of China)", "name_ar" => "تايوان (جمهورية الصين)", "flag" => env('APP_URL')."assets/Flags/tw.png"],
            ["code" => "TZ", "name_en" => "Tanzania, United Republic of", "name_ar" => "تنزانيا", "flag" => env('APP_URL')."assets/Flags/tz.png"],
            ["code" => "UA", "name_en" => "Ukraine", "name_ar" => "أوكرانيا", "flag" => env('APP_URL')."assets/Flags/ua.png"],
            ["code" => "UG", "name_en" => "Uganda", "name_ar" => "أوغندا", "flag" => env('APP_URL')."assets/Flags/ug.png"],
            ["code" => "UM", "name_en" => "US Minor Outlying Islands", "name_ar" => "جزر الولايات المتحدة الصغيرة النائية", "flag" => env('APP_URL')."assets/Flags/um.png"],
            ["code" => "US", "name_en" => "United States", "name_ar" => "الولايات المتحدة الأمريكية", "flag" => env('APP_URL')."assets/Flags/us.png"],
            ["code" => "UY", "name_en" => "Uruguay", "name_ar" => "أوروغواي", "flag" => env('APP_URL')."assets/Flags/uy.png"],
            ["code" => "UZ", "name_en" => "Uzbekistan", "name_ar" => "أوزبكستان", "flag" => env('APP_URL')."assets/Flags/uz.png"],
            ["code" => "VA", "name_en" => "Holy See (Vatican City State)", "name_ar" => "الكرسي الرسولي (دولة مدينة الفاتيكان)", "flag" => env('APP_URL')."assets/Flags/va.png"],
            ["code" => "VC", "name_en" => "Saint Vincent and the Grenadines", "name_ar" => "سانت فينسنت والغرينادين", "flag" => env('APP_URL')."assets/Flags/vc.png"],
            ["code" => "VE", "name_en" => "Venezuela, Bolivarian Republic of", "name_ar" => "فنزويلا (الجمهورية البوليفارية)", "flag" => env('APP_URL')."assets/Flags/ve.png"],
            ["code" => "VG", "name_en" => "Virgin Islands, British", "name_ar" => "جزر العذراء البريطانية", "flag" => env('APP_URL')."assets/Flags/vg.png"],
            ["code" => "VI", "name_en" => "Virgin Islands, U.S.", "name_ar" => "جزر العذراء الأمريكية", "flag" => env('APP_URL')."assets/Flags/vi.png"],
            ["code" => "VN", "name_en" => "Vietnam", "name_ar" => "فيتنام", "flag" => env('APP_URL')."assets/Flags/vn.png"],
            ["code" => "VU", "name_en" => "Vanuatu", "name_ar" => "فانواتو", "flag" => env('APP_URL')."assets/Flags/vu.png"],
            ["code" => "WF", "name_en" => "Wallis and Futuna Islands", "name_ar" => "واليس وفوتونا", "flag" => env('APP_URL')."assets/Flags/wf.png"],
            ["code" => "WS", "name_en" => "Samoa", "name_ar" => "ساموا", "flag" => env('APP_URL')."assets/Flags/ws.png"],
            ["code" => "XK", "name_en" => "Kosovo", "name_ar" => "كوسوفو", "flag" => env('APP_URL')."assets/Flags/xk.png"],
            ["code" => "YE", "name_en" => "Yemen", "name_ar" => "اليمن", "flag" => env('APP_URL')."assets/Flags/ye.png"],
            ["code" => "YT", "name_en" => "Mayotte", "name_ar" => "مايوت", "flag" => env('APP_URL')."assets/Flags/yt.png"],
            ["code" => "ZA", "name_en" => "South Africa", "name_ar" => "جنوب أفريقيا", "flag" => env('APP_URL')."assets/Flags/za.png"],
            ["code" => "ZM", "name_en" => "Zambia", "name_ar" => "زامبيا", "flag" => env('APP_URL')."assets/Flags/zm.png"],
            ["code" => "ZW", "name_en" => "Zimbabwe", "name_ar" => "زيمبابوي", "flag" => env('APP_URL')."assets/Flags/zw.png"]
        ];
        DB::table('countries')->insert($countries);
    }
}
