<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LookupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lookups')->delete();

        DB::table('lookups')->insert([
            ['code' =>       'U-Category',         'key' => 'C-Local',             'value' => '1'],
            ['code' =>       'U-Category',         'key' => 'C-Regional',          'value' => '2'],
            ['code' =>       'U-Category',         'key' => 'C-Global',            'value' => '3'],

            ['code' =>       'U-OperatorType',     'key' => 'OT-fixed',            'value' => 'Fixed'],
            ['code' =>       'U-OperatorType',     'key' => 'OT-percentage',       'value' => 'Percentage'],
            ['code' =>       'U-Content',          'key' => 'C-about_us',          'value' => 'This is content (About Us)'],
            ['code' =>       'U-Content',          'key' => 'C-privacy_policy',    'value' => 'This is content (Privacy Policy)'],
            ['code' =>       'U-Content',          'key' => 'C-FAQ',               'value' => 'This is content (FAQ)'],
            ['code' =>       'U-Content',          'key' => 'C-terms_conditions',  'value' => 'This is content (Terms & Conditions)'],
            ['code' =>       'U-Content',          'key' => 'C-sliders',           'value' => 'This is content (Sliders)'],

            ['code' =>       'U-StatusOrder',      'key' => 'SO-submit_order' ,    'value' => 'Submit order'],
            ['code' =>       'U-StatusOrder',      'key' => 'SO-success' ,         'value' => 'Success'],
            ['code' =>       'U-StatusOrder',      'key' => 'SO-failed'  ,         'value' => 'Failed' ],
            ['code' =>       'U-StatusOrder',      'key' => 'SO-charged' ,         'value' => 'Charged'],

            ['code' =>       'U-StatusBilling',    'key' => 'SB-success' ,         'value' => 'Success'],
            ['code' =>       'U-StatusBilling',    'key' => 'SB-failed'  ,         'value' => 'Failed' ],
            ['code' =>       'U-StatusBilling',    'key' => 'SB-pending' ,         'value' => 'Pending'],
            ['code' =>       'U-StatusBilling',    'key' => 'SB-start_payment' ,   'value' => 'Start-Payment'],

            ['code' =>       'U-StatusPackage',    'key' => 'SP-new' ,             'value' => 'New'],
            ['code' =>       'U-StatusPackage',    'key' => 'SP-current' ,         'value' => 'Current'],
            ['code' =>       'U-StatusPackage',    'key' => 'SP-archived' ,        'value' => 'Archived'],

            ['code' =>       'U-PromocodeType',    'key' => 'PCT-global' ,         'value' => 'Global'],
            ['code' =>       'U-PromocodeType',    'key' => 'PCT-item' ,           'value' => 'Item'],
            ['code' =>       'U-PromocodeType',    'key' => 'PCT-category',        'value' => 'Category'],
            ['code' =>       'U-PromocodeType',    'key' => 'PCT-sub_category' ,   'value' => 'Sub_Category'],
            ['code' =>       'U-PromocodeType',    'key' => 'PCT-user' ,           'value' => 'User'],
            // counrtries
            ['code' =>       'U-Country',          'key' => 'C-AF',                 'value' => "Afghanistan",          ],
            ['code' =>       'U-Country',          'key' => 'C-AL',                 'value' => "Albania",              ],
            ['code' =>       'U-Country',          'key' => 'C-DZ',                 'value' => "Algeria",              ],
            ['code' =>       'U-Country',          'key' => 'C-AS',                 'value' => "American Samoa",       ],
            ['code' =>       'U-Country',          'key' => 'C-AD',                 'value' => "Andorra",              ],
            ['code' =>       'U-Country',          'key' => 'C-AO',                 'value' => "Angola",               ],
            ['code' =>       'U-Country',          'key' => 'C-AI',                 'value' => "Anguilla",             ],
            ['code' =>       'U-Country',          'key' => 'C-AQ',                 'value' => "Antarctica",           ],
            ['code' =>       'U-Country',          'key' => 'C-AG',                 'value' => "Antigua And Barbuda",  ],
            ['code' =>       'U-Country',          'key' => 'C-AR',                 'value' => "Argentina",            ],
            ['code' =>       'U-Country',          'key' => 'C-AM',                 'value' => "Armenia",              ],
            ['code' =>       'U-Country',          'key' => 'C-AW',                 'value' => "Aruba",                ],
            ['code' =>       'U-Country',          'key' => 'C-AU',                 'value' => "Australia",            ],
            ['code' =>       'U-Country',          'key' => 'C-AT',                 'value' => "Austria",              ],
            ['code' =>       'U-Country',          'key' => 'C-AZ',                 'value' => "Azerbaijan",           ],
            ['code' =>       'U-Country',          'key' => 'C-BS',                 'value' => "Bahamas The",          ],
            ['code' =>       'U-Country',          'key' => 'C-BH',                 'value' => "Bahrain",              ],
            ['code' =>       'U-Country',          'key' => 'C-BD',                 'value' => "Bangladesh",           ],
            ['code' =>       'U-Country',          'key' => 'C-BB',                 'value' => "Barbados",             ],
            ['code' =>       'U-Country',          'key' => 'C-BY',                 'value' => "Belarus",              ],
            ['code' =>       'U-Country',          'key' => 'C-BE',                 'value' => "Belgium",              ],
            ['code' =>       'U-Country',          'key' => 'C-BZ',                 'value' => "Belize",               ],
            ['code' =>       'U-Country',          'key' => 'C-BJ',                 'value' => "Benin",                ],
            ['code' =>       'U-Country',          'key' => 'C-BM',                 'value' => "Bermuda",              ],
            ['code' =>       'U-Country',          'key' => 'C-BT',                 'value' => "Bhutan",               ],
            ['code' =>       'U-Country',          'key' => 'C-BO',                 'value' => "Bolivia",              ],
            ['code' =>       'U-Country',          'key' => 'C-BA',                 'value' => "Bosnia and Herzegovina",       ],
            ['code' =>       'U-Country',          'key' => 'C-BW',                 'value' => "Botswana",                     ],
            ['code' =>       'U-Country',          'key' => 'C-BV',                 'value' => "Bouvet Island",              ],
            ['code' =>       'U-Country',          'key' => 'C-BR',                 'value' => "Brazil",                      ],
            ['code' =>       'U-Country',          'key' => 'C-IO',                 'value' => "British Indian Ocean Territory"],
            ['code' =>       'U-Country',          'key' => 'C-BN',                 'value' => "Brunei",                       ],
            ['code' =>       'U-Country',          'key' => 'C-BG',                 'value' => "Bulgaria",                     ],
            ['code' =>       'U-Country',          'key' => 'C-BF',                 'value' => "Burkina Faso",                 ],
            ['code' =>       'U-Country',          'key' => 'C-BI',                 'value' => "Burundi",                      ],
            ['code' =>       'U-Country',          'key' => 'C-KH',                 'value' => "Cambodia",                     ],
            ['code' =>       'U-Country',          'key' => 'C-CM',                 'value' => "Cameroon",                     ],
            ['code' =>       'U-Country',          'key' => 'C-CA',                 'value' => "Canada",                       ],
            ['code' =>       'U-Country',          'key' => 'C-CV',                 'value' => "Cape Verde",                   ],
            ['code' =>       'U-Country',          'key' => 'C-KY',                 'value' => "Cayman Islands",               ],
            ['code' =>       'U-Country',          'key' => 'C-CF',                 'value' => "Central African Republic",     ],
            ['code' =>       'U-Country',          'key' => 'C-TD',                 'value' => "Chad",                         ],
            ['code' =>       'U-Country',          'key' => 'C-CL',                 'value' => "Chile",                       ],
            ['code' =>       'U-Country',          'key' => 'C-CN',                 'value' => "China",                       ],
            ['code' =>       'U-Country',          'key' => 'C-CX',                 'value' => "Christmas Island",            ],
            ['code' =>       'U-Country',          'key' => 'C-CC',                 'value' => "Cocos (Keeling) Islands",      ],
            ['code' =>       'U-Country',          'key' => 'C-CO',                 'value' => "Colombia",                    ],
            ['code' =>       'U-Country',          'key' => 'C-KM',                 'value' => "Comoros",                      ],
            ['code' =>       'U-Country',          'key' => 'C-CG',                 'value' => "Congo",                        ],
            ['code' =>       'U-Country',          'key' => 'C-CD',                 'value' => "Congo The Democratic Republic Of The"],
            ['code' =>       'U-Country',          'key' => 'C-CK',                 'value' => "Cook Islands"],
            ['code' =>       'U-Country',          'key' => 'C-CR',                 'value' => "Costa Rica"],
            ['code' =>       'U-Country',          'key' => 'C-CI',                 'value' => "Cote D Ivoire (Ivory Coast)"],
            ['code' =>       'U-Country',          'key' => 'C-HR',                 'value' => "Croatia (Hrvatska)"],
            ['code' =>       'U-Country',          'key' => 'C-CU',                 'value' => "Cuba"],
            ['code' =>       'U-Country',          'key' => 'C-CY',                 'value' => "Cyprus"],
            ['code' =>       'U-Country',          'key' => 'C-CZ',                 'value' => "Czech Republic"],
            ['code' =>       'U-Country',          'key' => 'C-DK',                 'value' => "Denmark"],
            ['code' =>       'U-Country',          'key' => 'C-DJ',                 'value' => "Djibouti"],
            ['code' =>       'U-Country',          'key' => 'C-DM',                 'value' => "Dominica", ],
            ['code' =>       'U-Country',          'key' => 'C-DO',                 'value' => "Dominican Republic", ],
            ['code' =>       'U-Country',          'key' => 'C-TP',                 'value' => "East Timor"],
            ['code' =>       'U-Country',          'key' => 'C-EC',                 'value' => "Ecuador"],
            ['code' =>       'U-Country',          'key' => 'C-EG',                 'value' => "Egypt"],
            ['code' =>       'U-Country',          'key' => 'C-SV',                 'value' => "El Salvador"],
            ['code' =>       'U-Country',          'key' => 'C-GQ',                 'value' => "Equatorial Guinea"],
            ['code' =>       'U-Country',          'key' => 'C-ER',                 'value' => "Eritrea"],
            ['code' =>       'U-Country',          'key' => 'C-EE',                 'value' => "Estonia"],
            ['code' =>       'U-Country',          'key' => 'C-ET',                 'value' => "Ethiopia"],
            ['code' =>       'U-Country',          'key' => 'C-XA',                 'value' => "External Territories of Australia"],
            ['code' =>       'U-Country',          'key' => 'C-FK',                 'value' => "Falkland Islands"],
            ['code' =>       'U-Country',          'key' => 'C-FO',                 'value' => "Faroe Islands"],
            ['code' =>       'U-Country',          'key' => 'C-FJ',                 'value' => "Fiji Islands"],
            ['code' =>       'U-Country',          'key' => 'C-FI',                 'value' => "Finland"],
            ['code' =>       'U-Country',          'key' => 'C-FR',                 'value' => "France"],
            ['code' =>       'U-Country',          'key' => 'C-GF',                 'value' => "French Guiana"],
            ['code' =>       'U-Country',          'key' => 'C-PF',                 'value' => "French Polynesia"],
            ['code' =>       'U-Country',          'key' => 'C-TF',                 'value' => "French Southern Territories"],
            ['code' =>       'U-Country',          'key' => 'C-GA',                 'value' => "Gabon"],
            ['code' =>       'U-Country',          'key' => 'C-GM',                 'value' => "Gambia The"],
            ['code' =>       'U-Country',          'key' => 'C-GE',                 'value' => "Georgia"],
            ['code' =>       'U-Country',          'key' => 'C-DE',                 'value' => "Germany"],
            ['code' =>       'U-Country',          'key' => 'C-GH',                 'value' => "Ghana"],
            ['code' =>       'U-Country',          'key' => 'C-GI',                 'value' => "Gibraltar"],
            ['code' =>       'U-Country',          'key' => 'C-GR',                 'value' => "Greece"],
            ['code' =>       'U-Country',          'key' => 'C-GL',                 'value' => "Greenland"],
            ['code' =>       'U-Country',          'key' => 'C-GD',                 'value' => "Grenada", ],
            ['code' =>       'U-Country',          'key' => 'C-GP',                 'value' => "Guadeloupe"],
            ['code' =>       'U-Country',          'key' => 'C-GU',                 'value' => "Guam", ],
            ['code' =>       'U-Country',          'key' => 'C-GT',                 'value' => "Guatemala"],
            ['code' =>       'U-Country',          'key' => 'C-XU',                 'value' => "Guernsey and Alderney"],
            ['code' =>       'U-Country',          'key' => 'C-GN',                 'value' => "Guinea"],
            ['code' =>       'U-Country',          'key' => 'C-GW',                 'value' => "Guinea-Bissau"],
            ['code' =>       'U-Country',          'key' => 'C-GY',                 'value' => "Guyana"],
            ['code' =>       'U-Country',          'key' => 'C-HT',                 'value' => "Haiti"],
            ['code' =>       'U-Country',          'key' => 'C-HM',                 'value' => "Heard and McDonald Islands"],
            ['code' =>       'U-Country',          'key' => 'C-HN',                 'value' => "Honduras"],
            ['code' =>       'U-Country',          'key' => 'C-HK',                 'value' => "Hong Kong S.A.R."],
            ['code' =>       'U-Country',          'key' => 'C-HU',                 'value' => "Hungary"],
            ['code' =>       'U-Country',          'key' => 'C-IS',                 'value' => "Iceland"],
            ['code' =>       'U-Country',          'key' => 'C-IN',                 'value' => "India"],
            ['code' =>       'U-Country',          'key' => 'C-ID',                 'value' => "Indonesia"],
            ['code' =>       'U-Country',          'key' => 'C-IR',                 'value' => "Iran"],
            ['code' =>       'U-Country',          'key' => 'C-IQ',                 'value' => "Iraq"],
            ['code' =>       'U-Country',          'key' => 'C-IE',                 'value' => "Ireland"],
            ['code' =>       'U-Country',          'key' => 'C-IL',                 'value' => "Israel"],
            ['code' =>       'U-Country',          'key' => 'C-IT',                 'value' => "Italy"],
            ['code' =>       'U-Country',          'key' => 'C-JM',                 'value' => "Jamaica", ],
            ['code' =>       'U-Country',          'key' => 'C-JP',                 'value' => "Japan"],
            ['code' =>       'U-Country',          'key' => 'C-XJ',                 'value' => "Jersey"],
            ['code' =>       'U-Country',          'key' => 'C-JO',                 'value' => "Jordan"],
            ['code' =>       'U-Country',          'key' => 'C-KZ',                 'value' => "Kazakhstan"],
            ['code' =>       'U-Country',          'key' => 'C-KE',                 'value' => "Kenya"],
            ['code' =>       'U-Country',          'key' => 'C-KI',                 'value' => "Kiribati"],
            ['code' =>       'U-Country',          'key' => 'C-KP',                 'value' => "Korea North"],
            ['code' =>       'U-Country',          'key' => 'C-KR',                 'value' => "Korea South"],
            ['code' =>       'U-Country',          'key' => 'C-KW',                 'value' => "Kuwait"],
            ['code' =>       'U-Country',          'key' => 'C-KG',                 'value' => "Kyrgyzstan"],
            ['code' =>       'U-Country',          'key' => 'C-LA',                 'value' => "Laos"],
            ['code' =>       'U-Country',          'key' => 'C-LV',                 'value' => "Latvia"],
            ['code' =>       'U-Country',          'key' => 'C-LB',                 'value' => "Lebanon"],
            ['code' =>       'U-Country',          'key' => 'C-LS',                 'value' => "Lesotho"],
            ['code' =>       'U-Country',          'key' => 'C-LR',                 'value' => "Liberia"],
            ['code' =>       'U-Country',          'key' => 'C-LY',                 'value' => "Libya"],
            ['code' =>       'U-Country',          'key' => 'C-LI',                 'value' => "Liechtenstein"],
            ['code' =>       'U-Country',          'key' => 'C-LT',                 'value' => "Lithuania"],
            ['code' =>       'U-Country',          'key' => 'C-LU',                 'value' => "Luxembourg"],
            ['code' =>       'U-Country',          'key' => 'C-MO',                 'value' => "Macau S.A.R."],
            ['code' =>       'U-Country',          'key' => 'C-MK',                 'value' => "Macedonia"],
            ['code' =>       'U-Country',          'key' => 'C-MG',                 'value' => "Madagascar"],
            ['code' =>       'U-Country',          'key' => 'C-MW',                 'value' => "Malawi"],
            ['code' =>       'U-Country',          'key' => 'C-MY',                 'value' => "Malaysia"],
            ['code' =>       'U-Country',          'key' => 'C-MV',                 'value' => "Maldives"],
            ['code' =>       'U-Country',          'key' => 'C-ML',                 'value' => "Mali"],
            ['code' =>       'U-Country',          'key' => 'C-MT',                 'value' => "Malta"],
            ['code' =>       'U-Country',          'key' => 'C-XM',                 'value' => "Man (Isle of)"],
            ['code' =>       'U-Country',          'key' => 'C-MH',                 'value' => "Marshall Islands"],
            ['code' =>       'U-Country',          'key' => 'C-MQ',                 'value' => "Martinique"],
            ['code' =>       'U-Country',          'key' => 'C-MR',                 'value' => "Mauritania"],
            ['code' =>       'U-Country',          'key' => 'C-MU',                 'value' => "Mauritius"],
            ['code' =>       'U-Country',          'key' => 'C-YT',                 'value' => "Mayotte"],
            ['code' =>       'U-Country',          'key' => 'C-MX',                 'value' => "Mexico"],
            ['code' =>       'U-Country',          'key' => 'C-FM',                 'value' => "Micronesia"],
            ['code' =>       'U-Country',          'key' => 'C-MD',                 'value' => "Moldova"],
            ['code' =>       'U-Country',          'key' => 'C-MC',                 'value' => "Monaco"],
            ['code' =>       'U-Country',          'key' => 'C-MN',                 'value' => "Mongolia"],
            ['code' =>       'U-Country',          'key' => 'C-MS',                 'value' => "Montserrat", ],
            ['code' =>       'U-Country',          'key' => 'C-MA',                 'value' => "Morocco"],
            ['code' =>       'U-Country',          'key' => 'C-MZ',                 'value' => "Mozambique"],
            ['code' =>       'U-Country',          'key' => 'C-MM',                 'value' => "Myanmar"],
            ['code' =>       'U-Country',          'key' => 'C-NA',                 'value' => "Namibia"],
            ['code' =>       'U-Country',          'key' => 'C-NR',                 'value' => "Nauru"],
            ['code' =>       'U-Country',          'key' => 'C-NP',                 'value' => "Nepal"],
            ['code' =>       'U-Country',          'key' => 'C-AN',                 'value' => "Netherlands Antilles"],
            ['code' =>       'U-Country',          'key' => 'C-NL',                 'value' => "Netherlands The"],
            ['code' =>       'U-Country',          'key' => 'C-NC',                 'value' => "New Caledonia"],
            ['code' =>       'U-Country',          'key' => 'C-NZ',                 'value' => "New Zealand"],
            ['code' =>       'U-Country',          'key' => 'C-NI',                 'value' => "Nicaragua"],
            ['code' =>       'U-Country',          'key' => 'C-NE',                 'value' => "Niger"],
            ['code' =>       'U-Country',          'key' => 'C-NG',                 'value' => "Nigeria"],
            ['code' =>       'U-Country',          'key' => 'C-NU',                 'value' => "Niue"],
            ['code' =>       'U-Country',          'key' => 'C-NF',                 'value' => "Norfolk Island"],
            ['code' =>       'U-Country',          'key' => 'C-MP',                 'value' => "Northern Mariana Islands", ],
            ['code' =>       'U-Country',          'key' => 'C-NO',                 'value' => "Norway"],
            ['code' =>       'U-Country',          'key' => 'C-OM',                 'value' => "Oman"],
            ['code' =>       'U-Country',          'key' => 'C-PK',                 'value' => "Pakistan"],
            ['code' =>       'U-Country',          'key' => 'C-PW',                 'value' => "Palau"],
            ['code' =>       'U-Country',          'key' => 'C-PS',                 'value' => "Palestinian Territory Occupied"],
            ['code' =>       'U-Country',          'key' => 'C-PA',                 'value' => "Panama"],
            ['code' =>       'U-Country',          'key' => 'C-PG',                 'value' => "Papua new Guinea"],
            ['code' =>       'U-Country',          'key' => 'C-PY',                 'value' => "Paraguay"],
            ['code' =>       'U-Country',          'key' => 'C-PE',                 'value' => "Peru"],
            ['code' =>       'U-Country',          'key' => 'C-PH',                 'value' => "Philippines"],
            ['code' =>       'U-Country',          'key' => 'C-PN',                 'value' => "Pitcairn Island"],
            ['code' =>       'U-Country',          'key' => 'C-PL',                 'value' => "Poland"],
            ['code' =>       'U-Country',          'key' => 'C-PT',                 'value' => "Portugal"],
            ['code' =>       'U-Country',          'key' => 'C-PR',                 'value' => "Puerto Rico", ],
            ['code' =>       'U-Country',          'key' => 'C-QA',                 'value' => "Qatar"],
            ['code' =>       'U-Country',          'key' => 'C-RE',                 'value' => "Reunion"],
            ['code' =>       'U-Country',          'key' => 'C-RO',                 'value' => "Romania"],
            ['code' =>       'U-Country',          'key' => 'C-RU',                 'value' => "Russia"],
            ['code' =>       'U-Country',          'key' => 'C-RW',                 'value' => "Rwanda"],
            ['code' =>       'U-Country',          'key' => 'C-SH',                 'value' => "Saint Helena"],
            ['code' =>       'U-Country',          'key' => 'C-KN',                 'value' => "Saint Kitts And Nevis", ],
            ['code' =>       'U-Country',          'key' => 'C-LC',                 'value' => "Saint Lucia"],
            ['code' =>       'U-Country',          'key' => 'C-PM',                 'value' => "Saint Pierre and Miquelon"],
            ['code' =>       'U-Country',          'key' => 'C-VC',                 'value' => "Saint Vincent And The Grenadines", ],
            ['code' =>       'U-Country',          'key' => 'C-WS',                 'value' => "Samoa"],
            ['code' =>       'U-Country',          'key' => 'C-SM',                 'value' => "San Marino"],
            ['code' =>       'U-Country',          'key' => 'C-ST',                 'value' => "Sao Tome and Principe"],
            ['code' =>       'U-Country',          'key' => 'C-SA',                 'value' => "Saudi Arabia"],
            ['code' =>       'U-Country',          'key' => 'C-SN',                 'value' => "Senegal"],
            ['code' =>       'U-Country',          'key' => 'C-RS',                 'value' => "Serbia"],
            ['code' =>       'U-Country',          'key' => 'C-SC',                 'value' => "Seychelles"],
            ['code' =>       'U-Country',          'key' => 'C-SL',                 'value' => "Sierra Leone"],
            ['code' =>       'U-Country',          'key' => 'C-SG',                 'value' => "Singapore"],
            ['code' =>       'U-Country',          'key' => 'C-SK',                 'value' => "Slovakia"],
            ['code' =>       'U-Country',          'key' => 'C-SI',                 'value' => "Slovenia"],
            ['code' =>       'U-Country',          'key' => 'C-XG',                 'value' => "Smaller Territories of the UK"],
            ['code' =>       'U-Country',          'key' => 'C-SB',                 'value' => "Solomon Islands"],
            ['code' =>       'U-Country',          'key' => 'C-SO',                 'value' => "Somalia"],
            ['code' =>       'U-Country',          'key' => 'C-ZA',                 'value' => "South Africa"],
            ['code' =>       'U-Country',          'key' => 'C-GS',                 'value' => "South Georgia"],
            ['code' =>       'U-Country',          'key' => 'C-SS',                 'value' => "South Sudan"],
            ['code' =>       'U-Country',          'key' => 'C-ES',                 'value' => "Spain"],
            ['code' =>       'U-Country',          'key' => 'C-LK',                 'value' => "Sri Lanka"],
            ['code' =>       'U-Country',          'key' => 'C-SD',                 'value' => "Sudan"],
            ['code' =>       'U-Country',          'key' => 'C-SR',                 'value' => "Surivalue"],
            ['code' =>       'U-Country',          'key' => 'C-SJ',                 'value' => "Svalbard And Jan Mayen Islands"],
            ['code' =>       'U-Country',          'key' => 'C-SZ',                 'value' => "Swaziland"],
            ['code' =>       'U-Country',          'key' => 'C-SE',                 'value' => "Sweden"],
            ['code' =>       'U-Country',          'key' => 'C-CH',                 'value' => "Switzerland"],
            ['code' =>       'U-Country',          'key' => 'C-SY',                 'value' => "Syria"],
            ['code' =>       'U-Country',          'key' => 'C-TW',                 'value' => "Taiwan"],
            ['code' =>       'U-Country',          'key' => 'C-TJ',                 'value' => "Tajikistan"],
            ['code' =>       'U-Country',          'key' => 'C-TZ',                 'value' => "Tanzania"],
            ['code' =>       'U-Country',          'key' => 'C-TH',                 'value' => "Thailand"],
            ['code' =>       'U-Country',          'key' => 'C-TG',                 'value' => "Togo"],
            ['code' =>       'U-Country',          'key' => 'C-TK',                 'value' => "Tokelau"],
            ['code' =>       'U-Country',          'key' => 'C-TO',                 'value' => "Tonga"],
            ['code' =>       'U-Country',          'key' => 'C-TT',                 'value' => "Trinidad And Tobago", ],
            ['code' =>       'U-Country',          'key' => 'C-TN',                 'value' => "Tunisia"],
            ['code' =>       'U-Country',          'key' => 'C-TR',                 'value' => "Turkey"],
            ['code' =>       'U-Country',          'key' => 'C-TM',                 'value' => "Turkmenistan"],
            ['code' =>       'U-Country',          'key' => 'C-TC',                 'value' => "Turks And Caicos Islands", ],
            ['code' =>       'U-Country',          'key' => 'C-TV',                 'value' => "Tuvalu"],
            ['code' =>       'U-Country',          'key' => 'C-UG',                 'value' => "Uganda"],
            ['code' =>       'U-Country',          'key' => 'C-UA',                 'value' => "Ukraine"],
            ['code' =>       'U-Country',          'key' => 'C-AE',                 'value' => "United Arab Emirates"],
            ['code' =>       'U-Country',          'key' => 'C-GB',                 'value' => "United Kingdom"],
            ['code' =>       'U-Country',          'key' => 'C-US',                 'value' => "United States"],
            ['code' =>       'U-Country',          'key' => 'C-UM',                 'value' => "United States Minor Outlying Islands"],
            ['code' =>       'U-Country',          'key' => 'C-UY',                 'value' => "Uruguay"],
            ['code' =>       'U-Country',          'key' => 'C-UZ',                 'value' => "Uzbekistan"],
            ['code' =>       'U-Country',          'key' => 'C-VU',                 'value' => "Vanuatu"],
            ['code' =>       'U-Country',          'key' => 'C-VA',                 'value' => "Vatican City State (Holy See)"],
            ['code' =>       'U-Country',          'key' => 'C-VE',                 'value' => "Venezuela"],
            ['code' =>       'U-Country',          'key' => 'C-VN',                 'value' => "Vietnam"],
            ['code' =>       'U-Country',          'key' => 'C-VG',                 'value' => "Virgin Islands (British)", ],
            ['code' =>       'U-Country',          'key' => 'C-VI',                 'value' => "Virgin Islands (US)"],
            ['code' =>       'U-Country',          'key' => 'C-WF',                 'value' => "Wallis And Futuna Islands"],
            ['code' =>       'U-Country',          'key' => 'C-EH',                 'value' => "Western Sahara"],
            ['code' =>       'U-Country',          'key' => 'C-YE',                 'value' => "Yemen"],
            ['code' =>       'U-Country',          'key' => 'C-YU',                 'value' => "Yugoslavia"],
            ['code' =>       'U-Country',          'key' => 'C-ZM',                 'value' => "Zambia"],
            ['code' =>       'U-Country',          'key' => 'C-ZW',                 'value' => "Zimbabwe"],


            // Enum For Countries
            // ..............
        ]);
    }
}
